namespace Eticaret.Infrastructure.Utils;

public static class NameChanger
{
    public static string ReplaceInvalidChars(string name) 
        => name.Replace("İ", "I")
            .Replace("ı", "i")
            .Replace("Ğ", "G")
            .Replace("ğ", "g")
            .Replace("Ü", "U")
            .Replace("ü", "u")
            .Replace("ş", "s")
            .Replace("Ş", "S")
            .Replace("Ö", "O")
            .Replace("ö", "o")
            .Replace("Ç", "C")
            .Replace("ç", "c")
            .Replace("é", "")
            .Replace("!", "")
            .Replace("'", "")
            .Replace("^", "")
            .Replace("+", "")
            .Replace("%", "")
            .Replace("/", "")
            .Replace("(", "")
            .Replace(")", "")
            .Replace("=", "")
            .Replace("?", "")
            .Replace("_", "")
            .Replace("*", "")
            .Replace("æ", "")
            .Replace("ß", "")
            .Replace("@", "")
            .Replace("€", "")
            .Replace("<", "")
            .Replace(">", "")
            .Replace("#", "")
            .Replace("$", "")
            .Replace("½", "")
            .Replace("{", "")
            .Replace("[", "")
            .Replace("]", "")
            .Replace("}", "")
            .Replace(@"\", "")
            .Replace("|", "")
            .Replace("~", "")
            .Replace("¨", "")
            .Replace(",", "")
            .Replace(";", "")
            .Replace("`", "")
            .Replace(".", "")
            .Replace(":", "")
            .Replace(" ", "");
}